project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "blog_gsoc"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/anjaninandan001
      - icon: linkedin
        href: https://www.linkedin.com/in/anjani-nandan-8567a2281/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



